version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    groups:
      gatsby:
        patterns:
          - "gatsby*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
